BEGIN TRANSACTION;
ALTER TABLE rate ADD COLUMN estado VARCHAR(20) DEFAULT 'activo';
ALTER TABLE rate ADD COLUMN fecha_creacion DATETIME DEFAULT '2005-01-01 10:00:00';
ALTER TABLE rate ADD COLUMN fecha_cierre DATETIME;
ALTER TABLE rate ADD COLUMN hided_digits INTEGER DEFAULT 0;
ALTER TABLE rate ADD COLUMN idParent INTEGER DEFAULT 0;
COMMIT;
