ALTER TABLE presentity CHANGE COLUMN body body BLOB NOT NULL;
ALTER TABLE rls_presentity CHANGE COLUMN presence_state presence_state BLOB NOT NULL;
ALTER TABLE silo CHANGE COLUMN body body BLOB NOT NULL;
ALTER TABLE xcap CHANGE COLUMN doc doc MEDIUMBLOB NOT NULL;
